; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Title Screen II
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env3,@env5,@env0 ; 00 : Square lead
	.word @env8,@env3,@env6,@env1 ; 01 : Square harm
	.word @env2,@env3,@env4,@env0 ; 02 : Triangle bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$00,$11
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $c2,$7f,$00,$00
@env6:
	.byte $c1,$7f,$00,$00
@env7:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c7,$c6,$00,$08
@env8:
	.byte $00,$cb,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $20, $ff, $ed, $48, $23, $ff, $ed, $48, $1c, $cd, $19, $ff, $9d, $48, $1d, $cd, $20, $ff, $9d, $48
	.byte $41, $10
	.word @song0ref6
@song0ref29:
	.byte $48, $a7, $00, $a5, $2c, $a5, $2a, $a5, $2c, $a5, $2d, $a5, $48, $2c, $ff, $9d, $00, $af, $2c, $87, $2a, $87, $28, $87
	.byte $48, $25, $ff, $9d, $00, $a5, $2c, $87, $2a, $87, $28, $87, $25, $87, $48, $24, $cd, $27, $cd, $2c, $cd
	.byte $41, $0b
	.word @song0ref29
	.byte $48, $2f, $cd, $2d, $cd, $2c, $cd, $48, $2c, $a5, $2d, $a5, $28, $ff, $9d, $48, $2c, $a5, $2d, $a5, $27, $ff, $9d, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $82
@song0ref105:
	.byte $19, $cd, $1b, $cd, $1c, $cd, $20, $f5, $1e, $a5, $20, $a5, $21, $a5, $20, $cd, $1c, $ff, $9d, $20, $cd, $1b, $cd, $1c
	.byte $cd
	.byte $41, $19
	.word @song0ref105
	.byte $41, $19
	.word @song0ref105
	.byte $41, $19
	.word @song0ref105
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84
@song0ref144:
	.byte $19, $91, $00, $91, $20, $91, $00, $91, $28, $91, $00, $91, $27, $91, $00, $91, $28, $91, $00, $91, $20, $91, $00, $91
	.byte $1c, $91, $00, $91, $20, $91, $00, $91, $23, $91, $00, $91, $26, $91, $00, $91, $23, $91, $00, $91, $26, $91, $00, $91
	.byte $1c, $91, $00, $91, $21, $91, $00, $91, $25, $91, $00, $91, $28, $91, $00, $91, $2c, $91, $00, $91, $28, $91, $00, $91
	.byte $19, $91, $00, $91, $1b, $91, $00, $91, $1d, $91, $00, $91, $20, $91, $00, $91, $1d, $91, $00, $91, $20, $91, $00, $91
	.byte $41, $60
	.word @song0ref144
	.byte $41, $60
	.word @song0ref144
	.byte $41, $60
	.word @song0ref144
	.byte $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref254:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $0a
	.word @song0ref254
	.byte $41, $0a
	.word @song0ref254
	.byte $ff, $ef, $42
	.word @song0ch3loop
