; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 5
	.word @instruments
	.word @samples-4
; 00 : Game Over
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Going In
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Going Down
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Going Up
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Going Home
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env11,@env6,@env8,@env0 ; 00 : French Horn (tri)
	.word @env3,@env6,@env10,@env7 ; 01 : Trumpet (square)
	.word @env5,@env6,@env9,@env2 ; 02 : Instrument 2 (square)
	.word @env4,@env6,@env8,@env0 ; 03 : Instrument 1
	.word @env1,@env6,@env9,@env0 ; 04 : Drums (noise)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ce,$cb,$c8,$c4,$c2,$c0,$00,$06
@env2:
	.byte $00,$c0,$04,$bf,$06,$be,$02,$bf,$bf,$c0,$02,$bf,$02,$be,$05,$c0,$c1,$bf,$00,$11
@env3:
	.byte $00,$cf,$cd,$cb,$c9,$00,$04
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $00,$cb,$14,$ca,$06,$c9,$00,$05
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$00,$40
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $c1,$7f,$00,$00
@env11:
	.byte $00,$cb,$c8,$c5,$c3,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $82, $25, $b5, $00, $81, $24, $85, $00, $23, $85, $00, $24
	.byte $a1, $00, $81, $23, $a1, $00, $81, $24, $a1, $00, $81, $29, $a5, $28, $a1, $00, $81, $2b, $a1, $00, $81, $48, $29, $a5
	.byte $2e, $a5, $2c, $a5, $2b, $a5, $2c, $91, $29, $91, $2a, $91, $28, $91, $29, $91, $24, $91, $25, $91, $22, $91, $48, $24
	.byte $c5, $00, $85, $20, $a5, $1d, $a5, $20, $b9, $22, $87, $20, $87, $1f, $a3, $00, $1d, $a3, $00, $48, $1d, $ff, $83, $00
	.byte $83, $1d, $87, $24, $87, $29, $f5, $00, $a5
@song0ref98:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $0c
	.word @song0ref98
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $11, $8f, $00, $11, $8f, $00, $11, $8f, $00, $0c
@song0ref135:
	.byte $91, $11, $91, $10, $91, $11, $91, $0c, $91
@song0ref144:
	.byte $11, $91, $10, $91, $11, $91, $0c, $91, $0d, $91, $0a, $91, $0c, $91, $13
	.byte $41, $11
	.word @song0ref135
	.byte $41, $0f
	.word @song0ref144
	.byte $91
@song0ref166:
	.byte $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00
	.byte $41, $0c
	.word @song0ref166
	.byte $1c, $8f, $00, $1c, $8f, $00, $1c, $8f, $00, $1c
@song0ref191:
	.byte $8f, $00, $18, $8f, $00, $18, $8f, $00, $18, $8f, $00, $18
	.byte $41, $0c
	.word @song0ref191
	.byte $41, $0c
	.word @song0ref191
	.byte $8f, $00, $1d, $b7, $00, $1d, $8f, $00, $1d, $b9, $00, $91
@song0ref221:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84, $1d, $a5, $22, $a5, $20, $a5, $25, $a5, $24, $a5, $20, $a5, $22, $a5, $1f, $a5, $20, $a5, $1d, $a5, $1f, $a5, $1c
	.byte $a5, $1d, $a5, $18, $a5, $19, $a5, $1c, $a5, $1d, $a5, $20, $a5, $1f, $a5, $1c, $a5, $18, $a5, $1d, $a5, $1c, $a5, $1f
	.byte $a5, $1d, $a5, $18, $a5, $14, $a5, $13, $a5, $11, $ff, $97, $00, $83
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch3loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $86, $19, $b5, $00, $99, $19, $b5, $1b, $99, $1d, $99, $22
	.byte $99, $48, $20, $ed, $00, $99, $1b, $b5, $1d, $99, $48, $1d, $ed, $00, $ed, $48, $ff, $8b, $16, $99, $18, $99, $19, $99
	.byte $48, $d3, $00, $b5, $19, $99, $1b, $99, $19, $99, $48, $d3, $00, $b5, $19, $99, $1b, $99, $1d, $99, $48, $b7, $00, $99
	.byte $1d, $b5, $1e, $99, $1d, $99, $19, $99, $48, $1b, $ed, $00, $ed, $48, $ff, $df, $48, $ff, $df, $48, $ff, $df, $48, $ff
	.byte $df, $48, $ff, $df, $48, $ff, $df, $48, $ff, $df, $48, $ff, $df, $42
	.word @song1ch0loop
@song1ch4:
@song1ch1:
@song1ch1loop:
@song1ref107:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	.byte $41, $0e
	.word @song1ref107
	.byte $ff, $df, $ff, $df, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80, $25, $d1, $24, $d1, $20, $b5, $22, $d1, $20, $d1, $1b, $99, $1d, $99, $ff, $8b, $00, $d1, $ff, $c3, $20, $99, $19
	.byte $ff, $a5, $00, $99, $1b, $99, $19, $ff, $a5, $00, $99, $1e, $99, $1d, $ff, $a5, $00, $99, $19, $99, $20, $ff, $a5, $00
	.byte $b5
	.byte $41, $0e
	.word @song1ref107
	.byte $ff, $df, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $86
@song1ref191:
	.byte $19, $83, $00, $af, $19, $83, $00, $af, $19, $83, $00, $af, $19, $83, $00, $af
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $10
	.word @song1ref191
	.byte $41, $0e
	.word @song1ref107
	.byte $42
	.word @song1ch3loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ef, $48, $ff, $b3, $82
@song2ref11:
	.byte $14, $8d, $00, $9b, $1b, $8b, $48, $19, $f5, $19, $f5, $48, $19, $f5, $00, $b9, $18, $9b, $00, $8d, $16, $8b, $48, $18
	.byte $8d, $00, $8b, $14, $8d, $00, $8b, $0f, $b9, $00, $f5, $48, $ff, $b3
	.byte $41, $1c
	.word @song2ref11
	.byte $1b, $b9, $00, $f5, $48, $ff, $b3
	.byte $41, $22
	.word @song2ref11
	.byte $41, $22
	.word @song2ref11
@song2ref65:
	.byte $20, $b9, $48, $1f, $b9, $20, $b9, $22, $b9, $24, $b9, $48, $25, $b9, $00, $9b, $25, $8d, $24, $8b, $22, $8d, $00, $8b
	.byte $24, $8d, $00, $8b, $25, $8d, $00, $8b, $22, $8d, $00, $8b, $48, $24, $8d, $00, $9b, $27, $8b, $27, $f5, $00, $b9, $48
	.byte $ff, $b3
	.byte $41, $2d
	.word @song2ref65
	.byte $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $ff, $ef, $ff, $ef, $ff, $b3, $84, $0f, $b9, $11, $f5, $00, $f5, $0f, $8d, $00, $a9, $08, $b9, $00, $f5, $ff, $ef, $ff
	.byte $b3, $0f, $b9, $11, $f5, $00, $f5, $0f, $8d, $00, $a9, $0c, $b9, $00, $f5
@song2ref180:
	.byte $ff, $b3, $27, $8d, $00, $9b, $24, $8b, $25, $ff, $ed, $1d, $f5, $00, $b9, $20, $9b, $00, $8d, $22, $8b, $24, $8d, $00
	.byte $8b, $20, $8d, $00, $8b, $27, $d7, $00, $d7
	.byte $41, $1d
	.word @song2ref180
	.byte $20, $b9, $00, $f5
@song2ref220:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $80
@song2ref255:
	.byte $20, $8d, $00, $8b, $20, $8d, $00, $a9, $20, $87, $00, $83, $20, $83, $00, $85, $20, $8d, $00, $8b, $20, $8d, $00, $c7
	.byte $20, $8d, $00, $8b, $20, $8d, $00, $a9, $20, $87, $00, $83, $20, $83, $00, $85, $20, $8d, $00, $8b, $20, $8d, $00, $c7
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
	.byte $41, $30
	.word @song2ref255
@song2ref327:
	.byte $1b, $ab, $00, $a9, $25, $8d, $00, $8b, $25, $ab, $00, $a9, $22, $8d, $00, $8b, $22, $ab, $00, $a9, $1f, $8d, $00, $8b
	.byte $1f, $ab, $00, $a9, $1d, $8d, $1f, $8b, $20, $ab, $00, $a9, $1b, $8d, $00, $8b, $1b, $ab, $00, $a9, $22, $8d, $00, $8b
	.byte $20, $ab, $00, $a9, $20, $9b, $1e, $9b, $00, $b9, $1f, $9b
	.byte $41, $3c
	.word @song2ref327
	.byte $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $88
@song2ref408:
	.byte $19, $9b, $19, $9b, $00, $9b, $19, $8d, $19, $8b, $19, $9b, $19, $9b, $00, $b9, $19, $9b, $19, $9b, $00, $9b, $19, $8d
	.byte $19, $8b, $19, $9b, $19, $9b, $00, $b9
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
	.byte $41, $20
	.word @song2ref408
@song2ref464:
	.byte $19, $8d, $00, $8b, $1e, $8d, $00, $8b, $19, $8d, $00, $8b, $22, $8d, $00, $8b, $19, $8d, $00, $8b, $1e, $8d, $00, $8b
	.byte $19, $8d, $00, $8b, $22, $8d, $19, $8b
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $41, $20
	.word @song2ref464
	.byte $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $1e
	.word @song2ref220
	.byte $41, $1e
	.word @song2ref220
	.byte $ff, $ef, $ff, $ef, $42
	.word @song2ch4loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $ff, $ff, $bf, $42
	.word @song3ch0loop
@song3ch4:
@song3ch3:
@song3ch2:
@song3ch1:
@song3ch1loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song3ch1loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $ff, $ff, $bf, $42
	.word @song4ch0loop
@song4ch4:
@song4ch3:
@song4ch2:
@song4ch1:
@song4ch1loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song4ch1loop
