; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for The Last Piece:
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_the_last_piece:=music_data_the_last_piece

music_data_the_last_piece:
	.byte 4
	.word @instruments
	.word @samples-4
; 00 : Going In
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Going Down
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Going Up
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Game Over
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_the_last_piece
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env12,@env6,@env8,@env0 ; 00 : French Horn (tri)
	.word @env2,@env6,@env9,@env10 ; 01 : Instrument 2 (square) soft
	.word @env1,@env6,@env9,@env0 ; 02 : Drums (noise)
	.word @env5,@env6,@env11,@env7 ; 03 : Trumpet (square)
	.word @env4,@env6,@env9,@env10 ; 04 : Instrument 2 (square)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ce,$cb,$c8,$c4,$c2,$c0,$00,$06
@env2:
	.byte $00,$c6,$0b,$c5,$0f,$c4,$00,$05
@env3:
	.byte $c0,$c4,$c7,$00,$00
@env4:
	.byte $00,$c9,$0d,$c8,$0d,$c7,$00,$05
@env5:
	.byte $00,$cf,$cd,$cb,$c9,$00,$04
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$c2,$c4,$c2,$c0,$be,$bc,$be,$c0,$00,$40
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $00,$c0,$c1,$c1,$c0,$c0,$bf,$be,$04,$c0,$c1,$0a,$c0,$bf,$bf,$be,$04,$c0,$00,$11
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $00,$cb,$c8,$c5,$c3,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $80, $2f, $af, $00, $87, $2a, $af, $00, $87, $28, $9b, $00, $87, $27, $af, $00, $87, $23, $af, $00, $87, $1c, $9b, $00
	.byte $87, $48, $1b, $ff, $ff, $bd
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref35:
	.byte $23, $cd, $00, $91, $1e, $91, $23, $91, $25, $91, $27, $b9, $25, $b9, $28, $a5, $48, $27, $b9, $23, $b9, $1e, $f5, $00
	.byte $cd, $48
	.byte $41, $14
	.word @song0ref35
	.byte $2a, $f5, $00, $cd, $48, $2c, $b7, $00, $2c, $91, $00, $91, $2c, $8f, $00, $2e, $91, $2f, $cd, $2a, $bd, $28, $a1, $48
	.byte $27, $b7, $00, $27, $91, $00, $91, $27, $8d, $00, $81, $28, $91, $2a, $cd, $28, $bd, $25, $a1, $48, $27, $b9, $23, $b9
	.byte $1e, $a5, $27, $b9, $25, $b9, $28, $a5, $48, $27, $ff, $9d, $25, $ff, $9d, $42
	.word @song0ch0loop
@song0ch1:
	.byte $82, $23, $b9, $25, $b9, $28, $a5, $2a, $b9, $28, $b9, $25, $a5, $27, $ff, $ff, $bd
@song0ch1loop:
	.byte $41, $10
	.word @song0ref35
	.byte $27, $b9, $23, $b9, $1e, $f5, $00, $cd, $27, $cd, $00, $91, $23, $91, $27, $91, $28, $91, $2a, $b9, $28, $b9, $2c, $a5
	.byte $2a, $b9, $23, $b9, $27, $f5, $00, $cd, $27, $91, $00, $a5, $25, $91, $00, $a5, $28, $91, $00, $a5, $27, $91, $00, $a5
	.byte $25, $91, $00, $91, $28, $91, $00
@song0ref206:
	.byte $91, $27, $91, $23, $91, $1e, $91, $27, $91, $23, $91, $1e, $91, $27, $91, $23, $91, $2a, $a5, $28, $a5, $27, $a5, $25
	.byte $a5, $23, $91, $20, $91, $1e, $91, $23, $91, $20, $91, $1e, $91, $23, $91, $25
	.byte $41, $12
	.word @song0ref206
	.byte $b7, $00, $2a, $91, $00, $a5, $2a, $91, $00, $a5, $2a, $91, $00, $a5, $2a, $91, $00, $91, $2a, $91, $00, $91, $42
	.word @song0ch1loop
@song0ch2:
	.byte $80, $23, $af, $00, $87, $23, $b9, $25, $a5, $27, $b1, $00, $85, $25, $b9, $28, $a5, $23, $9b, $00, $87, $23, $9b, $00
	.byte $87, $23, $9b, $00, $87, $23, $9b, $00, $23, $00, $23, $00, $23, $ff, $9d
@song0ch2loop:
@song0ref314:
	.byte $17, $8f, $00, $17, $8f, $00, $93, $17
@song0ref322:
	.byte $8f, $00, $17, $8f, $00, $17, $8f, $00, $93, $17, $8f, $00
	.byte $41, $14
	.word @song0ref314
	.byte $41, $14
	.word @song0ref314
	.byte $41, $14
	.word @song0ref314
	.byte $41, $14
	.word @song0ref314
	.byte $41, $14
	.word @song0ref314
	.byte $41, $14
	.word @song0ref314
	.byte $41, $10
	.word @song0ref314
	.byte $16, $8f, $00, $16
@song0ref359:
	.byte $8f, $00
@song0ref361:
	.byte $14, $8f, $00, $14, $8f, $00, $93, $14, $8f, $00, $14, $8f, $00, $14, $8f, $00, $93, $16
	.byte $41, $0c
	.word @song0ref322
	.byte $17, $8f, $00, $17, $8f, $00, $93, $19, $8f, $00, $1b, $8f, $00, $1b, $8f, $00, $93, $1b, $8f, $00, $1b, $8f, $00, $1b
	.byte $8f, $00, $93, $17
@song0ref410:
	.byte $8f, $00, $12, $8f, $00, $12, $8f, $00, $93, $12, $8f, $00, $12, $8f, $00, $12, $8f, $00, $93, $16, $91
	.byte $41, $11
	.word @song0ref361
	.byte $14
	.byte $41, $13
	.word @song0ref359
	.byte $14
	.byte $41, $13
	.word @song0ref410
	.byte $12
	.byte $41, $13
	.word @song0ref410
	.byte $12, $8f, $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $bf, $ff, $ff, $bf
@song0ch3loop:
	.byte $ff, $ff, $bf, $ff, $b3, $84, $25, $91, $2e, $91, $00, $91, $2e, $91, $00, $91, $2e
@song0ref476:
	.byte $91, $00, $91, $25, $91, $25, $91, $2f, $91, $00, $91, $25, $91, $25, $91, $2f
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $41, $10
	.word @song0ref476
	.byte $91, $00, $91, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $bf, $ff, $ff, $bf
@song0ch4loop:
@song0ref538:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref538
	.byte $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ef, $48, $ff, $b3, $86
@song1ref11:
	.byte $14, $8d, $00, $9b, $1b, $8b, $48, $19, $f5, $19, $f5, $48, $19, $f5, $00, $b9, $18, $9b, $00, $8d, $16, $8b, $48, $18
	.byte $8d, $00, $8b, $14, $8d, $00, $8b, $0f, $b9, $00, $f5, $48, $ff, $b3
	.byte $41, $1c
	.word @song1ref11
	.byte $1b, $b9, $00, $f5, $48, $ff, $b3
	.byte $41, $22
	.word @song1ref11
	.byte $41, $22
	.word @song1ref11
@song1ref65:
	.byte $20, $b9, $48, $1f, $b9, $20, $b9, $22, $b9, $24, $b9, $48, $25, $b9, $24, $b9, $22, $8d, $00, $8b, $24, $8d, $00, $8b
	.byte $25, $8d, $00, $8b, $22, $8d, $00, $8b, $48, $24, $8d, $00, $9b, $27, $8b, $27, $f5, $00, $b9, $48, $ff, $b3
	.byte $41, $2a
	.word @song1ref65
	.byte $20, $b9, $48, $1f, $b9, $20, $b9, $22, $b9, $24, $b9, $48, $25, $b9, $24, $b9, $22, $b9, $1f, $b9, $48, $20, $b9, $00
	.byte $9b, $20, $9b, $22, $b9, $00, $9b, $22, $9b, $48, $24, $b9, $00, $9b, $24, $9b, $25, $b9, $00, $9b, $25, $9b, $48, $27
	.byte $f5, $00, $9b, $27, $8b, $00, $27, $87, $00, $81, $27, $8b, $00, $8d, $27, $8b, $00, $8d, $48, $27, $ff, $b1, $00, $b9
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $ff, $ef, $ff, $ef, $ff, $b3, $88, $0f, $b9, $11, $f5, $00, $f5, $0f, $8d, $00, $a9, $08, $b9, $00, $f5, $ff, $ef, $ff
	.byte $b3, $0f, $b9, $11, $f5, $00, $f5, $0f, $8d, $00, $a9, $0c, $b9, $00, $f5
@song1ref229:
	.byte $ff, $b3, $27, $8d, $00, $9b, $24, $8b, $25, $ff, $ed, $1d, $f5, $00, $b9, $20, $9b, $00, $8d, $22, $8b, $24, $8d, $00
	.byte $8b, $20, $8d, $00, $8b, $27, $d7, $00, $d7
	.byte $41, $1d
	.word @song1ref229
	.byte $20, $b9, $00, $f5, $ff, $ef, $ff, $ef, $9d, $82
@song1ref275:
	.byte $27, $8d, $00, $8b, $27, $8d, $00, $8b, $29, $8d, $00, $8b, $27, $b9, $00, $b9, $bb, $24, $8d, $00, $8b, $24, $8d, $25
	.byte $8b, $24, $9b, $20, $9b, $1b, $b9, $00, $b9, $24, $8d, $00, $8b, $24, $8d, $25, $8b, $24, $9b, $20, $9b, $24, $b9, $00
	.byte $ff, $ed, $9d
	.byte $41, $2d
	.word @song1ref275
	.byte $1e, $b9, $1b, $8d, $00, $c7, $1b, $8d, $00, $8b, $1b, $8d, $00, $c7, $1b, $8d, $00, $8b, $22, $8d, $00, $c7, $1b, $8d
	.byte $00, $8b, $1b, $8d, $00, $c7, $1f, $8d, $00, $8b, $20, $8d, $00, $c7, $20, $8d, $00, $8b, $1f, $8d, $00, $c7, $1f, $8d
	.byte $00, $8b, $1e, $8d, $00, $c7, $1e, $8d, $00, $8b, $1d, $8d, $00, $c7, $1d, $8d, $00, $8b, $1b, $f5, $00, $9b, $1b, $8d
	.byte $00, $8b, $1b, $8d, $1f, $8b, $22, $8d, $25, $8b, $27, $f5, $00, $f5, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref420:
	.byte $20, $8d, $00, $8b, $20, $8d, $00, $a9, $20, $87, $00, $83, $20, $83, $00, $85, $20, $8d, $00, $8b, $20, $8d, $00, $c7
	.byte $20, $8d, $00, $8b, $20, $8d, $00, $a9, $20, $87, $00, $83, $20, $83, $00, $85, $20, $8d, $00, $8b, $20, $8d, $00, $c7
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
	.byte $41, $30
	.word @song1ref420
@song1ref492:
	.byte $1b, $ab, $00, $a9, $25, $8d, $00, $8b, $25, $ab, $00, $a9, $22, $8d, $00, $8b, $22, $ab, $00, $a9, $1f, $8d, $00, $8b
	.byte $1f, $ab, $00, $a9, $1d, $8d, $1f, $8b, $20, $ab, $00, $a9, $1b, $8d, $00, $8b, $1b, $ab, $00, $a9, $22, $8d, $00, $8b
	.byte $20, $ab, $00, $a9, $20, $9b, $1e, $9b, $00, $b9, $1f, $9b
	.byte $41, $3c
	.word @song1ref492
	.byte $41, $24
	.word @song1ref492
	.byte $1f, $8d, $20, $8b, $1b, $ab, $00, $a9, $16, $8d, $18, $8b, $19, $ab, $00, $a9, $18, $8d, $19, $8b, $1a, $9b, $00, $b9
	.byte $19, $8d, $20, $8b, $22, $e7, $00, $8b, $22, $8d, $00, $8b, $22, $8d, $1f, $8b, $20, $8d, $1d, $8b, $1f, $8d, $1a, $8b
	.byte $1b, $c9, $00, $8b, $1b, $8d, $16, $8b, $13, $d7, $00, $9b, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $84
@song1ref623:
	.byte $19, $9b, $19, $9b, $00, $9b, $19, $8d, $19, $8b, $19, $9b, $19, $9b, $00, $b9, $19, $9b, $19, $9b, $00, $9b, $19, $8d
	.byte $19, $8b, $19, $9b, $19, $9b, $00, $b9
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
	.byte $41, $20
	.word @song1ref623
@song1ref679:
	.byte $19, $8d, $00, $8b, $1e, $8d, $00, $8b, $19, $8d, $00, $8b, $22, $8d, $00, $8b, $19, $8d, $00, $8b, $1e, $8d, $00, $8b
	.byte $19, $8d, $00, $8b, $22, $8d, $19, $8b
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $41, $20
	.word @song1ref679
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref754:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef, $ff, $ef
	.byte $41, $1c
	.word @song1ref754
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $4c, $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4b, .lobyte(@env3), .hibyte(@env3), $86
@song2ref10:
	.byte $25, $89, $00, $4d, $25, $89, $00, $8d, $4d, $25, $89, $00, $8d, $4d
	.byte $41, $0b
	.word @song2ref10
	.byte $4d
	.byte $41, $0b
	.word @song2ref10
	.byte $4d, $25, $89, $00, $48, $4d, $25, $89, $00, $8d, $4d, $25
@song2ref43:
	.byte $89, $00, $8d, $4d, $26, $89, $00, $4d, $26, $89, $00, $8d, $4d, $26
	.byte $41, $0b
	.word @song2ref43
	.byte $41, $09
	.word @song2ref43
	.byte $48, $8d, $4d, $26
	.byte $41, $0b
	.word @song2ref43
@song2ref70:
	.byte $89, $00, $8d, $4d, $27, $89, $00, $4d, $27, $89, $00, $8d, $4d, $27
	.byte $41, $0a
	.word @song2ref70
	.byte $48, $4d, $27
	.byte $41, $0b
	.word @song2ref70
	.byte $41, $0b
	.word @song2ref70
	.byte $89, $00
@song2ref98:
	.byte $8d, $4d, $23, $89, $00, $4d, $23, $89, $00, $8d, $4d, $23, $89, $00, $48
	.byte $41, $0b
	.word @song2ref98
	.byte $8d, $4d, $23, $89, $00, $4d, $22, $89, $00, $4d, $23, $8b, $4d, $25, $8b, $4d, $27, $8b, $4d, $28, $8b, $4d, $27, $8b
	.byte $4d, $25, $8b, $4d, $23, $8b, $4d, $21, $8b, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $ff, $8b, $82, $24, $8b, $20, $8b, $1b, $8b, $17, $8b, $00, $99, $ff, $c3, $22, $8b, $1e, $8b, $19, $8b, $15, $8b, $00
	.byte $ff, $c1, $9b, $27, $8b, $23, $8b, $1e, $8b, $1a, $8b, $00, $ff, $89, $d3, $21, $8b, $23, $8b, $21, $8b, $23, $8b, $21
	.byte $8b, $23, $8b, $21, $8b, $23, $8b, $21, $8b, $00, $8b, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $80
@song2ref217:
	.byte $1b, $89, $00, $16, $89, $00, $1b, $89, $00, $1d, $89, $00, $1e, $89, $00, $1d, $89, $00
	.byte $41, $0c
	.word @song2ref217
	.byte $41, $12
	.word @song2ref217
	.byte $41, $0c
	.word @song2ref217
@song2ref244:
	.byte $19, $89, $00, $14, $89, $00, $19, $89, $00, $1b, $89, $00, $1c, $89, $00, $1b, $89, $00
	.byte $41, $0c
	.word @song2ref244
	.byte $41, $12
	.word @song2ref244
	.byte $41, $0c
	.word @song2ref244
@song2ref271:
	.byte $17, $89, $00, $12, $89, $00, $17, $89, $00, $19, $89, $00, $1a, $89, $00, $19, $89, $00
	.byte $41, $0c
	.word @song2ref271
	.byte $41, $12
	.word @song2ref271
	.byte $41, $0c
	.word @song2ref271
	.byte $17, $8b, $19, $8b, $1b, $8b, $17, $8b, $1b, $8b, $1c, $8b, $1e, $8b, $1b, $8b, $1e, $8b, $20, $8b, $1c, $8b, $1e, $8b
	.byte $1b, $8b, $1c, $8b, $19, $8b, $1a, $8b, $17, $8b, $18, $8b, $15, $8b, $17, $8b, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $84
@song2ref343:
	.byte $06, $8b, $0b, $8b, $06, $8b, $0b, $8b, $00, $8b, $0b, $8b, $06, $8b, $00, $8b, $0b, $8b, $00, $8b
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $41, $14
	.word @song2ref343
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
	.word @song2ch4loop
@song3ch0:
	.byte $86, $25, $b5, $00, $81, $24, $85, $00, $23, $85, $00, $24, $a1, $00, $81, $23, $a1, $00, $81, $24, $a1, $00, $81, $29
	.byte $a5, $28, $a1, $00, $81, $2b, $a1, $00, $81, $48, $29, $a5, $2e, $a5, $2c, $a5, $2b, $a5, $2c, $91, $29, $91, $2a, $91
	.byte $28, $91, $29, $91, $24, $91, $25, $91, $22, $91, $48, $24, $c5, $00, $85, $20, $a5, $1d, $a5, $20, $b9, $22, $87, $20
	.byte $87, $1f, $a3, $00, $1d, $a3, $00, $48, $1d, $ff, $83, $00, $83, $1d, $87, $24, $87, $29, $f5, $00, $a5, $44, $00
@song3ch1:
	.byte $80, $11, $8f, $00, $11, $8f, $00, $11, $8f, $00, $0c
@song3ref108:
	.byte $91, $11, $91, $10, $91, $11, $91, $0c, $91
@song3ref117:
	.byte $11, $91, $10, $91, $11, $91, $0c, $91, $0d, $91, $0a, $91, $0c, $91, $13
	.byte $41, $11
	.word @song3ref108
	.byte $41, $0f
	.word @song3ref117
	.byte $91
@song3ref139:
	.byte $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00
	.byte $41, $0c
	.word @song3ref139
	.byte $1c, $8f, $00, $1c, $8f, $00, $1c, $8f, $00, $1c
@song3ref164:
	.byte $8f, $00, $18, $8f, $00, $18, $8f, $00, $18, $8f, $00, $18
	.byte $41, $0c
	.word @song3ref164
	.byte $41, $0c
	.word @song3ref164
	.byte $8f, $00, $1d, $b7, $00, $1d, $8f, $00, $1d, $b9, $00, $91, $44, $00
@song3ch2:
	.byte $88, $1d, $a5, $22, $a5, $20, $a5, $25, $a5, $24, $a5, $20, $a5, $22, $a5, $1f, $a5, $20, $a5, $1d, $a5, $1f, $a5, $1c
	.byte $a5, $1d, $a5, $18, $a5, $19, $a5, $1c, $a5, $1d, $a5, $20, $a5, $1f, $a5, $1c, $a5, $18, $a5, $1d, $a5, $1c, $a5, $1f
	.byte $a5, $1d, $a5, $18, $a5, $14, $a5, $13, $a5, $11, $ff, $97, $00, $83, $44, $00
@song3ch4:
@song3ch3:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $44, $00
