; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_jump
	.word @sfx_ntsc_hit

@sfx_ntsc_jump:
	.byte $84,$6d,$85,$02,$83,$3d,$87,$6d,$88,$02,$86,$8d,$89,$f0,$01,$84
	.byte $cc,$85,$01,$83,$3b,$87,$cc,$88,$01,$86,$8b,$01,$84,$55,$83,$3a
	.byte $87,$55,$86,$8a,$01,$84,$1d,$83,$38,$87,$1d,$86,$88,$01,$84,$ef
	.byte $85,$00,$83,$36,$87,$ef,$88,$00,$86,$86,$01,$84,$cb,$83,$35,$87
	.byte $cb,$86,$85,$01,$84,$c5,$83,$33,$87,$c5,$86,$83,$01,$84,$e0,$83
	.byte $30,$87,$e0,$00
@sfx_ntsc_hit:
	.byte $87,$a8,$88,$01,$86,$8c,$8a,$83,$89,$3c,$01,$87,$69,$86,$8b,$8a
	.byte $80,$89,$3b,$01,$87,$47,$86,$89,$8a,$8e,$89,$39,$01,$87,$24,$8a
	.byte $8c,$01,$87,$1e,$86,$87,$89,$37,$01,$87,$28,$86,$85,$8a,$8d,$89
	.byte $35,$00

.export sounds
