; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env4,@env5,@env0 ; 00 : Instrument 1
	.word @env2,@env4,@env6,@env0 ; 01 : Instrument 3
	.word @env7,@env4,@env1,@env0 ; 02 : Instrument 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$c6,$7f,$00,$02
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $00,$cb,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $25, $b5, $00, $81, $24, $85, $00, $23, $85, $00, $24
	.byte $a1, $00, $81, $23, $a1, $00, $81, $24, $a1, $00, $81, $29, $a5, $28, $a1, $00, $81, $2b, $a1, $00, $81, $48, $29, $a5
	.byte $2e, $a5, $2c, $a5, $2b, $a5, $2c, $91, $29, $91, $2a, $91, $28, $91, $29, $91, $24, $91, $25, $91, $22, $91, $48, $24
	.byte $c5, $00, $85, $20, $a5, $1d, $a5, $20, $b9, $22, $87, $20, $87, $1f, $a3, $00, $1d, $a3, $00, $48, $1d, $ff, $83, $00
	.byte $83, $1d, $87, $24, $87, $29, $f5, $00, $a5
@song0ref98:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $0c
	.word @song0ref98
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $82, $11, $8f, $00, $11, $8f, $00, $11, $8f, $00, $0c
@song0ref135:
	.byte $91, $11, $91, $10, $91, $11, $91, $0c, $91
@song0ref144:
	.byte $11, $91, $10, $91, $11, $91, $0c, $91, $0d, $91, $0a, $91, $0c, $91, $13
	.byte $41, $11
	.word @song0ref135
	.byte $41, $0f
	.word @song0ref144
	.byte $91
@song0ref166:
	.byte $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00
	.byte $41, $0c
	.word @song0ref166
	.byte $1c, $8f, $00, $1c, $8f, $00, $1c, $8f, $00, $1c
@song0ref191:
	.byte $8f, $00, $18, $8f, $00, $18, $8f, $00, $18, $8f, $00, $18
	.byte $41, $0c
	.word @song0ref191
	.byte $41, $0c
	.word @song0ref191
	.byte $8f, $00, $1d, $b7, $00, $1d, $8f, $00, $1d, $b9, $00, $91
@song0ref221:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84, $1d, $a5, $22, $a5, $20, $a5, $25, $a5, $24, $a5, $20, $a5, $22, $a5, $1f, $a5, $20, $a5, $1d, $a5, $1f, $a5, $1c
	.byte $a5, $1d, $a5, $18, $a5, $19, $a5, $1c, $a5, $1d, $a5, $20, $a5, $1f, $a5, $1c, $a5, $18, $a5, $1d, $a5, $1c, $a5, $1f
	.byte $a5, $1d, $a5, $18, $a5, $14, $a5, $13, $a5, $11, $ff, $97, $00, $83
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $41, $0c
	.word @song0ref221
	.byte $42
	.word @song0ch3loop
